namespace Blip.Dealer.Desk.Manager.Models;

public static class Constants
{
    public const string BLIP_PLAN = "enterprise";
    public const string POSTMASTER = "postmaster@msging.net";
    public const string POSTMASTER_CRM = "postmaster@crm.msging.net";
    public const string POSTMASTER_BUILDER = "postmaster@builder.msging.net";
    public const string POSTMASTER_DESK = "postmaster@desk.msging.net";
    public const string DEFAULT_QUEUE = "Default";
    public const string QUEUE_NOT_EXIST_MESSAGE = "there are no saved queues";
    public const string GOOGLE_SHEET_IS_EMPTY = "Sheet is empty";

    public const string BOT_FACTORY_URL = "https://cwpjnln2-55598.brs.devtunnels.ms";
    public const string TOKEN = "eyJhbGciOiJSUzI1NiIsImtpZCI6IjYyN2JjMGZjOTZmZmNiMWM1NDRkZDY2NGI2ODQwYWNmIiwidHlwIjoiSldUIn0.eyJuYmYiOjE3MzA4OTM1MzYsImV4cCI6MTczMDkyMjMzNiwiaXNzIjoiaHR0cHM6Ly9hY2NvdW50LmJsaXAuYWkiLCJhdWQiOlsiaHR0cHM6Ly9hY2NvdW50LmJsaXAuYWkvcmVzb3VyY2VzIiwiYXBpLXBheW1lbnQtc2VydmljZSIsImFwaS1leHRlbnNpb24tc2VydmljZSJdLCJjbGllbnRfaWQiOiJibGlwLXBvcnRhbCIsInN1YiI6IjZhMjBiNmM3LTI0YzgtNDdiNy05YjkwLTBkZTZlNDUyMWIyMyIsImF1dGhfdGltZSI6MTczMDg5MzUzNiwiaWRwIjoiZ29vZ2xlIiwibmFtZSI6ImJydW5vLm5ha2F5YWJ1QGJsaXAuYWkiLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJicnVuby5uYWtheWFidUBibGlwLmFpIiwiZW1haWwiOiJicnVuby5uYWtheWFidUBibGlwLmFpIiwiUHJvdmlkZXJEaXNwbGF5TmFtZSI6Imdvb2dsZSIsIkZ1bGxOYW1lIjoiQnJ1bm8gTmFrYXlhYnUiLCJVc2VyTmFtZSI6ImJydW5vLm5ha2F5YWJ1QGJsaXAuYWkiLCJGaXJzdE5hbWUiOiJCcnVubyIsIlN1ck5hbWUiOiJOYWtheWFidSIsImN1bHR1cmUiOiJwdC1CUiIsIkNpdHkiOiJDdXJpdGliYSIsIkNvbXBhbnlOdW1iZXJPZkVtcGxveWVlcyI6IkJhbmQxMDAwXzEwMDAwIiwiQ29tcGFueVNpdGUiOiJodHRwczovL3d3dy50YWtlLm5ldC9ibGlwLyIsIlBob25lTnVtYmVyIjoiKzU1ICg0MSkgOTk4NTktNDU1MiIsIkVtYWlsIjoiYnJ1bm8ubmFrYXlhYnVAYmxpcC5haSIsIkVtYWlsQ29uZmlybWVkIjoiVHJ1ZSIsInNjb3BlIjpbIm9wZW5pZCIsInByb2ZpbGUiLCJlbWFpbCIsImFwaS1wYXltZW50LXNlcnZpY2UuZnVsbF9hY2Nlc3MiLCJhcGktZXh0ZW5zaW9uLXNlcnZpY2UuZnVsbF9hY2Nlc3MiLCJvZmZsaW5lX2FjY2VzcyJdLCJhbXIiOlsiZXh0ZXJuYWwiXX0.Zgnw29xUakMtupjmzEazB8jAeIt7CFohH0tVyJRLkwl1h0wBalJA2FAoSRaXEBUpZjpM9mvvcvbvPkGx5ZoNnD3N_HSdCKxCm5o167TKxXtLGIX7sMGH5L1klpuFUZuVCX6HATmRb5NnqTj41S9yLcLCrvRDBlRXirkrgXkH-nmitrVZPSL8sRpoWepSuL_ClEkKdf2T8UQn0li5OGFap4qZs_xT0Z-qk4aNWEziAfYHsWanrklGs53eX6JcGdnYcW_10qsQ5SPNNTEmKR2oQ3qmEdmi80AJ2TikGCfLD5FrM3i3NFwiMXXCvsQdQMZjH2xjs85T5teNKuLuyqU6aA";
    public const string BRAND = "FIAT";
    public const string SPREADSHEET_ID = "11SncilKtipNtsA2u4uHZG6S-9cEroUPgqkUGaYaPeDM";
    public const string SHEET_NAME = "BETA";
    public const string TENANT_ID = "fcagroup";
}